const NAV=[["Início","home"],["Política pública","politica"],["Colônia e Santas Casas","colonia"],["Campanhas e Oswaldo Cruz","campanhas"],["Previdência e INAMPS","previdencia"],["Alma-Ata e AIS","alma"],["Reforma e 8ª CNS","reforma"],["Constituição e leis","constituicao"],["Princípios do SUS","principios"],["Controle social","controle"],["Rede de atenção","rede"],["Pacto e futuro","futuro"],["Saúde bucal","bucal"],["Linha do tempo","linha"],["Galeria","galeria"],["Quiz","quiz"],["Glossário","glossario"]];
function banner(ph,k,t){return '<div class="banner"><div class="ph ph-'+ph+'"></div><div class="veil"></div><div class="t"><div class="kicker">'+k+'</div><h2>'+t+'</h2></div></div>'}
function cols(a,b){return '<div class="wrap cols"><div class="prose">'+a+'</div><div>'+b+'</div></div>'}
const PAGES={
home:'<section class="panel on" data-panel="home"><div class="hero"><div class="bg ph-equipe"></div><div class="veil"></div><div class="copy"><div class="kicker">Laboratório de leitura da apostila · 8 partes</div><h1>Como o Brasil passou do privilégio ao direito à saúde?</h1><p class="lede">Webapp visual da disciplina Políticas Públicas de Saúde no Brasil: colônia, campanhas, previdência, Reforma Sanitária, Constituição, leis 8.080 e 8.142, rede, pacto, saúde bucal e o SUS de 2030.</p><div class="cta"><button class="btn gold" data-go="politica">Começar pelo conceito</button><button class="btn ghost" data-go="linha">Linha do tempo</button><button class="btn ghost" data-go="quiz">Quiz</button></div></div></div><div class="wrap"><div class="statg"><div class="stat"><b>1543</b><span class="muted">Santa Casa de Santos</span></div><div class="stat"><b>1986</b><span class="muted">8ª Conferência Nacional de Saúde</span></div><div class="stat"><b>1988</b><span class="muted">Art. 196</span></div><div class="stat"><b>1990</b><span class="muted">Leis 8.080 e 8.142</span></div></div><h2>Mapa da apostila</h2><p class="muted">Clique em um módulo. O texto replica a apostila da Profª Adriana Beatriz Silveira Pinto.</p><div class="grid mods" id="modgrid"></div></div></section>',
politica:'<section class="panel" data-panel="politica">'+banner("hero","Parte 1","O que é uma política pública?")+cols('<p>Na apostila, política pública é o <b>conjunto das diretrizes e referenciais ético-legais adotados pelo Estado</b> para fazer frente a um problema que a sociedade lhe apresenta.</p><p>As políticas de saúde escolhem agenda, evidência, recurso, território e coalizão.</p><div class="quote">Política pública não é um post ou um mutirão. É diretriz + legalidade + ação contínua do Estado.</div>','<div class="photo ph-hero" data-cap="Identidade"></div><div class="box"><b>Seminário.</b> Qual problema sanitário do seu município ainda não virou agenda de Estado?</div>')+'</section>',
colonia:'<section class="panel" data-panel="colonia">'+banner("santacasa","Colônia e Império","389 anos sem política estruturada")+cols('<p>Na Colônia e no Império <b>não havia políticas públicas estruturadas</b>. O acesso dependia da classe. 1808: cursos no Rio e em Salvador. Santas Casas: Santos 1543, Salvador 1549, Rio 1567, São Paulo 1599, João Pessoa 1602, Belém 1619, Vitória 1818. Manaus: Santa Casa da Rua Dez de Julho, 1853–2004, crise em 1998. 1829: Sociedade de Medicina e Cirurgia do Rio.</p>','<div class="photo ph-santacasa" data-cap="Misericórdia"></div><div class="photo ph-amazonia" data-cap="Território ribeirinho"></div>')+'</section>',
campanhas:'<section class="panel" data-panel="campanhas">'+banner("oswaldo","República Velha","Oswaldo Cruz e a polícia sanitária")+cols('<p>1888: abolição e imigração. Vacina obrigatória contra a varíola. São Paulo cresce 2,72 vezes entre 1872 e 1900. 1910: febre amarela, portos e polícia sanitária. Revolta da Vacina em 1904. Carlos Chagas, 1920: educação sanitária.</p>','<div class="photo ph-oswaldo" data-cap="Oswaldo Cruz"></div><div class="photo ph-fiocruz" data-cap="Fiocruz"></div>')+'</section>',
previdencia:'<section class="panel" data-panel="previdencia">'+banner("hospital","1923–1977","Da CAP ao INAMPS")+cols('<p><b>1923 Lei Eloy Chaves</b>: CAPs. <b>1932</b>: IAPs. CLT 1943. INPS 1966 e INAMPS 1977. Lei 6.229/1975: MS no coletivo, Previdência no individual. INAMPS hospitalar exclui favela, periferia e zona rural.</p>','<div class="photo ph-hospital" data-cap="Hospital"></div>')+'</section>',
alma:'<section class="panel" data-panel="alma">'+banner("prenatal","1978–1984","Alma-Ata, Prev-Saúde e AIS")+cols('<p>Alma-Ata define saúde como bem-estar físico, mental e social. Prev-Saúde 1980. AIS 1984: semente dos conselhos e base do SUDS.</p>','<div class="photo ph-prenatal" data-cap="Atenção primária"></div>')+'</section>',
reforma:'<section class="panel" data-panel="reforma">'+banner("cns","1979–1987","Reforma Sanitária e a 8ª CNS")+cols('<p>1979: I Simpósio Nacional. Saúde como resultado das condições de vida. 8ª CNS (17 a 21/3/1986): 4.000 pessoas, 1.000 delegados. Temas: direito, sistema, financiamento. SUDS em 1987.</p>','<div class="photo ph-cns" data-cap="Conferência"></div><div class="photo ph-protesto" data-cap="Mobilização"></div>')+'</section>',
constituicao:'<section class="panel" data-panel="constituicao">'+banner("congresso","1988–1990","Art. 196 e as leis orgânicas")+'<div class="wrap"><div class="quote">A saúde é um direito de todos e dever do Estado — art. 196.</div>'+cols('<p>Universalização, descentralização, integralidade, participação. Leis 8.080 e 8.142 em 1990. Conceito ampliado da 8ª CNS: alimentação, habitação, educação, renda, ambiente, trabalho, terra e serviços.</p>','<div class="photo ph-congresso" data-cap="Congresso Nacional"></div>')+'</div></section>',
principios:'<section class="panel" data-panel="principios">'+banner("equity","Lei 8.080/90","Doutrina e organização")+'<div class="wrap"><div class="grid mods"><div class="card"><div class="bd"><h3>Universalidade</h3><p>Direito de todos.</p></div></div><div class="card"><div class="bd"><h3>Equidade</h3><p>Tratar desigualmente os desiguais.</p></div></div><div class="card"><div class="bd"><h3>Integralidade</h3><p>Promoção, proteção e recuperação.</p></div></div></div>'+cols('<p>Organizativos: descentralização, municipalização, regionalização, hierarquização, participação, resolutividade, intersetorialidade, complementaridade do privado. Lei 14.572/2023 — Brasil Sorridente.</p>','<div class="photo ph-equity" data-cap="Equidade"></div>')+'</div></section>',
controle:'<section class="panel" data-panel="controle">'+banner("vacina","Lei 8.142/90","Conferências e conselhos")+cols('<p>Conferência a cada 4 anos e Conselho permanente. Usuários com paridade de 50%. 17ª CNS em 2023; 18ª em 2027. CIB e CIT. NOB, NOAS, Decreto 7.508/2011.</p>','<div class="photo ph-vacina" data-cap="PNI"></div>')+'</section>',
rede:'<section class="panel" data-panel="rede">'+banner("samu","Estrutura viva","APS, especialidade e SAMU")+cols('<p>APS como porta de entrada. UBS: clínico, rastreamento, vacina, medicação básica, odontologia e ESF. SAMU 192: chamada, pré-hospitalar, triagem e encaminhamento.</p>','<div class="photo ph-samu" data-cap="SAMU"></div><div class="photo ph-equipe" data-cap="ESF"></div>')+'</section>',
futuro:'<section class="panel" data-panel="futuro">'+banner("acs","2006–2030","Pacto, clima e IA")+cols('<p>Pacto pela Saúde: Vida, Defesa do SUS e Gestão. Conquistas: PNI, ESF, HIV/Aids, SAMU. Desafios: financiamento, desigualdades, filas, envelhecimento, DCNTs, clima. A tecnologia deve cumprir 1988 — inclusive com o ACS na Amazônia.</p>','<div class="photo ph-acs" data-cap="ACS"></div>')+'</section>',
bucal:'<section class="panel" data-panel="bucal">'+banner("dental","Saúde bucal","Brasil Sorridente e Bangkok")+cols('<p>UBS/ESF, CEOs, laboratórios de prótese, CERs. Bangkok 2030: 80% com acesso, reduzir 10% das doenças, 50% dos países contra o açúcar.</p>','<div class="photo ph-dental" data-cap="Odontologia"></div>')+'</section>',
linha:'<section class="panel" data-panel="linha">'+banner("fiocruz","Síntese","Linha do tempo")+'<div class="wrap"><div class="tl" id="timeline"></div></div></section>',
galeria:'<section class="panel" data-panel="galeria">'+banner("amazonia","Acervo","Galeria")+'<div class="wrap"><div class="gallery" id="gal"></div></div></section>',
quiz:'<section class="panel" data-panel="quiz">'+banner("hero","Parte 8","Questões da apostila")+'<div class="wrap" id="quiz"></div></section>',
glossario:'<section class="panel" data-panel="glossario"><div class="wrap"><h2>Glossário operacional</h2><div id="glo"></div></div></section>'
};
